'''init

Revision ID: 72462ea7c18f
Revises:
Create Date: 2025-02-14 08:38:40.971273

'''
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '72462ea7c18f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bets",
        sa.Column("bet_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "state",
            sa.Enum("NEW", "FINISHED_WIN", "FINISHED_LOSE", name="betstate"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_bets_check_amount_positive")),
        sa.PrimaryKeyConstraint("bet_id", name=op.f("pk_bets")),
        sa.UniqueConstraint("bet_id", name=op.f("uq_bets_bet_id")),
    )
    op.create_unique_constraint(op.f("uq_bets_bet_id"), "bets", ["bet_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_bets_bet_id"), "bets", type_="unique")
    op.drop_table("bets")
    sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='betstate').drop(op.get_bind())
    # ### end Alembic commands ###
