"""events_table_added

Revision ID: 0d2df1ce8d1d
Revises: 72462ea7c18f
Create Date: 2025-02-15 18:58:58.713409

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0d2df1ce8d1d'
down_revision: Union[str, None] = '72462ea7c18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_events_event_id")),
    )
    op.create_unique_constraint(op.f('uq_events_event_id'), 'events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_events_event_id'), 'events', type_='unique')
    op.drop_table("events")
    # ### end Alembic commands ###
