version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: bet-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

    networks:
      - bets

volumes:
  postgres_data:


networks:
  bets:
    driver: bridge